wandb_version: 1

batch_size:
  desc: null
  value: 32
type:
  desc: null
  value: small
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1690527888.647367
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 51
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.5
      6: 4.30.2
      8:
      - 1
      - 2
      - 5
